# permissions for end users to edit composers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: composer-editor-role
rules:
- apiGroups:
  - serviceconnector.dev
  resources:
  - composers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - serviceconnector.dev
  resources:
  - composers/status
  verbs:
  - get
